print("When i was a young boy living in the city\n all i did was run run run run run.")
print("To infinity\n and beyond")
print(" A string is letters in brackets with quotations at the start and end of the bracket.")
print("An integer is numbers in brackets that equals another number when ran.")
print("A float is a number that has a decimal point in it.Eg 2.5")
print(543/3)
print(434/10)
print(555/2)
print(123/2)
print(123//2)
print(165//2)
print(2.5+6.5)
print(8+16)
print(2.5-8)
print(8-2.5)
print(69/69)
print(5*2.5)
print(8*8)
print(" Dylan "*10)
print("Dylan")
print("Dylan")
print("Dylan")
print("Dylan")
print("Dylan")
print("Dylan")
print("Dylan")
print("Dylan")
print("Dylan")
print("Dylan")
print("5+10="+str(5+10))
print("15/2="+str(7.5))
print("30/2*5="+str(75.0))
print("30/2*5="+str(75))