print(2+5)
print(5*5)
print(5-6)
print(10*100)
print(50/5)
print(60*60)
print(563889+87458346384)
print(4568/863463)
print("In this examplx and y are variables.")
x=2
y=5
print(x*y)
print(x+y)
print("This code is getting messy")
print("")
print("An easy way of creating a blank line")
print("\n")
print("this adds two blank lines as |n creates a new line")
name=input("What is your name?")
print(f"Hello {name}.")
age=input("what is your age?\n")
print(f"You are {age} years old")
print("generate a unique gamer name")
pet_name=input("what is your pets name?\n")
fav_colour=input("what is your favourite colour?\n")
last_ate=input("What was the last thing you ate ?\n")
print(f"cool!your gamer name is {pet_name}{fav_colour}{last_ate}")
book=input("What is your favourite book?\n")
movie=input("what is your favourite movie?\n")
game=input("what is your favourite game?\n")
print(f"cool, {book} is a great book. {movie} is my favourite movie too but {game} sucks,Supermario is much better.\n")
food=input("What is your favourite food?\n")
game=input("what is your favourite game?\n")
sport=input("what is your favourite sport?\n")
print(f"cool, {food} is a great food. {game} is my favourite game too. {sport} is my favourite sport aswell.\n")